# -*- coding: utf-8 -*-

"""
    ytelapi.models.activate_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class ActivateEnum(object):

    """Implementation of the 'Activate' enum.

    TODO: type enum description here.

    Attributes:
        MACTIVATE: TODO: type description here.
        DEACTIVATE: TODO: type description here.

    """

    MACTIVATE = 1

    DEACTIVATE = 0

