# -*- coding: utf-8 -*-

"""
    ytelapi.models.fileformat_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class FileformatEnum(object):

    """Implementation of the 'Fileformat' enum.

    TODO: type enum description here.

    Attributes:
        MP3: mp3 file
        WAV: wav file

    """

    MP3 = 'mp3'

    WAV = 'wav'

