# -*- coding: utf-8 -*-

"""
    ytelapi.models.http_action_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class HttpActionEnum(object):

    """Implementation of the 'HttpAction' enum.

    Types Of Method

    Attributes:
        GET: Get type
        POST: Post Type

    """

    GET = 'GET'

    POST = 'POST'

