# -*- coding: utf-8 -*-

"""
    ytelapi.models.interrupted_call_status_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class InterruptedCallStatusEnum(object):

    """Implementation of the 'InterruptedCallStatus' enum.

    Interrupted Call Status

    Attributes:
        CANCELED: Interrupt Call will be cancel
        COMPLETED: Interrupt Call is complete

    """

    CANCELED = 'canceled'

    COMPLETED = 'completed'

