# -*- coding: utf-8 -*-

"""
    ytelapi.models.merge_number_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class MergeNumberEnum(object):

    """Implementation of the 'MergeNumber' enum.

    TODO: type enum description here.

    Attributes:
        DELETE: TODO: type description here.
        MERGE: TODO: type description here.

    """

    DELETE = 0

    MERGE = 1

