# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.audio_direction_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class AudioDirectionEnum(object):

    """Implementation of the 'AudioDirection' enum.

    Audio Direction

    Attributes:
        IN: TODO: type description here.
        OUT: TODO: type description here.

    """

    IN = 'in'

    OUT = 'out'

