# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.direction_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class DirectionEnum(object):

    """Implementation of the 'Direction' enum.

    Play DTMF Direction & in play audio & sendDigit

    Attributes:
        IN: in direction
        OUT: out direction
        BOTH: both

    """

    IN = 'in'

    OUT = 'out'

    BOTH = 'both'

