# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.group_confirm_file_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class GroupConfirmFileEnum(object):

    """Implementation of the 'GroupConfirmFile' enum.

    TODO: type enum description here.

    Attributes:
        MP3: mp3 file
        WAV: wav file

    """

    MP3 = 'mp3'

    WAV = 'wav'

