# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.if_machine_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class IfMachineEnum(object):

    """Implementation of the 'ifMachine' enum.

    How Message360 should handle the receiving numbers voicemail machine

    Attributes:
        CONTINUE: TODO: type description here.
        HANGUP: TODO: type description here.

    """

    CONTINUE = 'continue'

    HANGUP = 'hangup'

