# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.m_activate_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class MActivateEnum(object):

    """Implementation of the 'mActivate' enum.

    TODO: type enum description here.

    Attributes:
        ACTIVATE: TODO: type description here.
        DEACTIVATE: TODO: type description here.

    """

    ACTIVATE = 1

    DEACTIVATE = 0

