# -*- coding: utf-8 -*-

"""
    ytelapiv3

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class NumbertypeEnum(object):

    """Implementation of the 'numbertype' enum.

    Number type either SMS,Voice or all

    Attributes:
        ALL: TODO: type description here.
        VOICE: TODO: type description here.
        SMS: TODO: type description here.

    """

    ALL = 'all'

    VOICE = 'voice'

    SMS = 'sms'

