# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.number_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class NumberTypeEnum(object):

    """Implementation of the 'Number Type' enum.

    Phone Number Type All,SMS or Voice

    Attributes:
        ALL: Get all phone Number type
        VOICE: Get only voice number type
        SMS: Get Only SMs number type

    """

    ALL = 'all'

    VOICE = 'voice'

    SMS = 'sms'

