# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.play_dtmf_direction_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class PlayDtmfDirectionEnum(object):

    """Implementation of the 'PlayDtmfDirection' enum.

    TODO: type enum description here.

    Attributes:
        IN: in direction
        OUT: out direction
        BOTH: both

    """

    IN = 'in'

    OUT = 'out'

    BOTH = 'both'

