# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.send_email_as_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class SendEmailAsEnum(object):

    """Implementation of the 'SendEmailAs' enum.

    send email TEXT or HTML format

    Attributes:
        TEXT: Email send as text format
        HTML: Email send as HTML format

    """

    TEXT = 'text'

    HTML = 'html'

