# -*- coding: utf-8 -*-

"""
    ytelapiv3

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class Status24Enum(object):

    """Implementation of the 'Status24' enum.

    TODO: type enum description here.

    Attributes:
        CANCELED: Interrupt Call will be cancel
        COMPLETED: Interrupt Call is complete

    """

    CANCELED = 'canceled'

    COMPLETED = 'completed'

