# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.status_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class StatusEnum(object):

    """Implementation of the 'Status' enum.

    Transcription Status

    Attributes:
        INPROGRESS: TODO: type description here.
        SUCCESS: TODO: type description here.
        FAILURE: TODO: type description here.

    """

    INPROGRESS = 'inprogress'

    SUCCESS = 'success'

    FAILURE = 'failure'

