# -*- coding: utf-8 -*-

"""
    ytelapiv3.models.type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class TypeEnum(object):

    """Implementation of the 'Type' enum.

    TODO: type enum description here.

    Attributes:
        TEXT: Email send as text format
        HTML: Email send as HTML format

    """

    TEXT = 'text'

    HTML = 'html'

