# -*- coding: utf-8 -*-

"""
    ytelapiv3

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class Type36Enum(object):

    """Implementation of the 'Type36' enum.

    TODO: type enum description here.

    Attributes:
        TEXT: Email send as text format
        HTML: Email send as HTML format

    """

    TEXT = 'text'

    HTML = 'html'

